
import { Contact, AppLanguage, Tool } from './types';

export const INITIAL_CONTACTS: Contact[] = [];

export const INITIAL_TOOLS: Tool[] = [
  {
    id: '1',
    name: 'PileUps',
    description: 'Advanced project stacking and task management utility.',
    url: 'https://pileups.vercel.app/',
    iconUrl: 'https://pileups.vercel.app/favicon.ico',
    category: 'Productivity'
  },
  {
    id: '2',
    name: 'Timeout',
    description: 'Focus timer and break management for productivity.',
    url: 'https://timeoutapps.vercel.app/',
    iconUrl: 'https://timeoutapps.vercel.app/favicon.ico',
    category: 'Productivity'
  },
  {
    id: '3',
    name: 'MindMap Files',
    description: 'Visual thinking and creative brainstorming workspace.',
    url: 'https://mindmapfiles.vercel.app/',
    iconUrl: 'https://mindmapfiles.vercel.app/favicon.ico',
    category: 'Productivity'
  }
];

export const SUPPORTED_LANGUAGES: { code: AppLanguage; name: string; nativeName: string; flag: string }[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
  { code: 'zh', name: 'Mandarin', nativeName: '中文', flag: '🇨🇳' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', flag: '🇰🇷' },
];

export const TRANSLATIONS: Record<AppLanguage, Record<string, string>> = {
  en: {
    title: "WingMentor HQ",
    masterDatabase: "Operations",
    sortLogic: "Sort Logic",
    company: "Company",
    position: "Position",
    custom: "Custom",
    allRecords: "All Records",
    customLists: "Custom Lists",
    groups: "Groups",
    status: "Status",
    synced: "SYNCED",
    saving: "SAVING...",
    entries: "Entries",
    searchPlaceholder: "Search records...",
    addRecord: "Add Record",
    settings: "System Settings",
    appearance: "Appearance",
    language: "Language",
    maintenance: "Maintenance",
    purgeDatabase: "Restore Database",
    factoryReset: "Reset app to factory defaults",
    closeSettings: "Close Settings",
    modify: "Modify",
    erase: "Erase",
    joined: "Joined",
    dbRegistry: "DB Registry",
    identity: "Identity",
    action: "Action",
    givenName: "Given Name",
    surname: "Surname",
    emailAddress: "Email Address",
    phone: "Mobile/Phone number",
    profilePicture: "Profile Picture",
    registryDate: "Registry Date",
    remarks: "Remarks",
    discard: "Discard",
    confirmRegistry: "Confirm Registry",
    updateProfile: "Update Profile",
    clearSelection: "Clear Selection",
    noEntries: "No Entries Found",
    noEntriesSub: "Create your first employee profile or adjust your filters to populate the directory.",
    createProfile: "Create Profile",
    personnel: "Employee",
    privatePractice: "Private Practice",
    filteredView: "Filtered View",
    fullDatabaseIndex: "Full Database Index",
    masterDirectory: "Team Directory",
    allRecordsLabel: "All Personnel",
    darkUI: "Dark UI",
    lightUI: "Light UI",
    toggleTheme: "Toggle system interface theme",
    tools: "Company Apps",
    launchTool: "Launch Tool",
    addTool: "Add App",
    toolUrl: "Application URL",
    toolName: "Application Name",
    browserError: "If the application refuses to connect, it may block embedded views.",
    openExternal: "Open in New Tab",
    overview: "Company Overview",
    revenue: "Total Revenue",
    activeProjects: "Active Projects",
    teamGrowth: "Team Growth",
    efficiency: "Efficiency Score",
    quickApps: "Quick Apps",
    performance: "Performance Trajectory",
    timeline: "Progress Timeline",
    mindmap: "Mindmap",
    sales: "Sales & Products",
    marketing: "Marketing",
    planning: "Planning Room",
    document: "Strategy Doc",
    simulation: "Simulator"
  },
  fr: {
    title: "WingMentor QG",
    masterDatabase: "Opérations",
    sortLogic: "Logique de tri",
    company: "Entreprise",
    position: "Poste",
    custom: "Personnalisé",
    allRecords: "Tous les dossiers",
    customLists: "Listes personnalisées",
    groups: "Groupes",
    status: "Statut",
    synced: "SYNCHRONISÉ",
    saving: "ENREGISTREMENT...",
    entries: "Entrées",
    searchPlaceholder: "Rechercher...",
    addRecord: "Ajouter un dossier",
    settings: "Paramètres système",
    appearance: "Apparence",
    language: "Langue",
    maintenance: "Maintenance",
    purgeDatabase: "Restaurer la base de données",
    factoryReset: "Réinitialiser l'application",
    closeSettings: "Fermer les paramètres",
    modify: "Modifier",
    erase: "Effacer",
    joined: "Inscrit le",
    dbRegistry: "Registre BD",
    identity: "Identité",
    action: "Action",
    givenName: "Prénom",
    surname: "Nom",
    emailAddress: "Adresse e-mail",
    phone: "Téléphone",
    profilePicture: "Photo de profil",
    registryDate: "Date d'enregistrement",
    remarks: "Remarques",
    discard: "Annuler",
    confirmRegistry: "Confirmer l'inscription",
    updateProfile: "Mettre à jour le profil",
    clearSelection: "Effacer la sélection",
    noEntries: "Aucune entrée trouvée",
    noEntriesSub: "Créez votre premier profil d'employé ou ajustez vos filtres.",
    createProfile: "Créer un profil",
    personnel: "Employé",
    privatePractice: "Cabinet privé",
    filteredView: "Vue filtrée",
    fullDatabaseIndex: "Index complet de la base",
    masterDirectory: "Répertoire d'équipe",
    allRecordsLabel: "Tout le personnel",
    darkUI: "Interface Sombre",
    lightUI: "Interface Claire",
    toggleTheme: "Basculer le thème de l'interface",
    tools: "Apps d'entreprise",
    launchTool: "Lancer l'outil",
    addTool: "Ajouter un outil",
    toolUrl: "URL de l'application",
    toolName: "Nom de l'application",
    browserError: "Si l'application refuse de se connecter, elle peut bloquer les vues intégrées.",
    openExternal: "Ouvrir dans un nouvel onglet",
    overview: "Aperçu de l'entreprise",
    revenue: "Revenu total",
    activeProjects: "Projets actifs",
    teamGrowth: "Croissance de l'équipe",
    efficiency: "Score d'efficacité",
    quickApps: "Apps Rapides",
    performance: "Trajectoire de performance",
    timeline: "Chronologie des progrès",
    mindmap: "Carte heuristique",
    sales: "Ventes et produits",
    marketing: "Marketing",
    planning: "Salle de planification",
    document: "Document stratégique",
    simulation: "Simulateur"
  },
  de: {
    title: "WingMentor Zentrale",
    masterDatabase: "Operationen",
    sortLogic: "Sortierlogik",
    company: "Unternehmen",
    position: "Position",
    custom: "Benutzerdefiniert",
    allRecords: "Alle Datensätze",
    customLists: "Eigene Listen",
    groups: "Gruppen",
    status: "Status",
    synced: "SYNCHRONISIERT",
    saving: "SPEICHERN...",
    entries: "Einträge",
    searchPlaceholder: "Suchen...",
    addRecord: "Datensatz hinzufügen",
    settings: "Systemeinstellungen",
    appearance: "Aussehen",
    language: "Sprache",
    maintenance: "Wartung",
    purgeDatabase: "Datenbank wiederherstellen",
    factoryReset: "App zurücksetzen",
    closeSettings: "Einstellungen schließen",
    modify: "Bearbeiten",
    erase: "Löschen",
    joined: "Beigetreten",
    dbRegistry: "DB-Eintrag",
    identity: "Identität",
    action: "Aktion",
    givenName: "Vorname",
    surname: "Nachname",
    emailAddress: "E-Mail-Adresse",
    phone: "Telefonnummer",
    profilePicture: "Profilbild",
    registryDate: "Registrierungsdatum",
    remarks: "Bemerkungen",
    discard: "Verwerfen",
    confirmRegistry: "Registrierung bestätigen",
    updateProfile: "Profil aktualisieren",
    clearSelection: "Auswahl aufheben",
    noEntries: "Keine Einträge gefunden",
    noEntriesSub: "Erstellen Sie Ihr erstes Mitarbeiterprofil oder passen Sie die Filter an.",
    createProfile: "Profil erstellen",
    personnel: "Mitarbeiter",
    privatePractice: "Privatpraxis",
    filteredView: "Gefilterte Ansicht",
    fullDatabaseIndex: "Vollständiger Datenbankindex",
    masterDirectory: "Teamverzeichnis",
    allRecordsLabel: "Gesamtes Personal",
    darkUI: "Dunkles Design",
    lightUI: "Helles Design",
    toggleTheme: "Systemdesign umschalten",
    tools: "Unternehmens-Apps",
    launchTool: "Werkzeug starten",
    addTool: "Werkzeug hinzufügen",
    toolUrl: "Anwendungs-URL",
    toolName: "Anwendungsname",
    browserError: "Wenn die Anwendung die Verbindung verweigert, blockiert sie möglicherweise eingebettete Ansichten.",
    openExternal: "In neuem Tab öffnen",
    overview: "Unternehmensübersicht",
    revenue: "Gesamtumsatz",
    activeProjects: "Aktive Projekte",
    teamGrowth: "Teamwachstum",
    efficiency: "Effizienzwert",
    quickApps: "Schnell-Apps",
    performance: "Leistungsverlauf",
    timeline: "Fortschritts-Zeitleiste",
    mindmap: "Mindmap",
    sales: "Vertrieb & Produkte",
    marketing: "Marketing",
    planning: "Planungsraum",
    document: "Strategiepapier",
    simulation: "Simulator"
  },
  ru: {
    title: "WingMentor Штаб",
    masterDatabase: "Операции",
    sortLogic: "Логика сортировки",
    company: "Компания",
    position: "Должность",
    custom: "Свои",
    allRecords: "Все записи",
    customLists: "Свои списки",
    groups: "Группы",
    status: "Статус",
    synced: "СИНХРОНИЗИРОВАНО",
    saving: "СОХРАНЕНИЕ...",
    entries: "Записи",
    searchPlaceholder: "Поиск...",
    addRecord: "Добавить запись",
    settings: "Настройки системы",
    appearance: "Оформление",
    language: "Язык",
    maintenance: "Обслуживание",
    purgeDatabase: "Восстановить базу данных",
    factoryReset: "Сбросить настройки",
    closeSettings: "Закрыть настройки",
    modify: "Изменить",
    erase: "Удалить",
    joined: "Присоединился",
    dbRegistry: "Запись в БД",
    identity: "Личность",
    action: "Действие",
    givenName: "Имя",
    surname: "Фамилия",
    emailAddress: "Электронная почта",
    phone: "Номер телефона",
    profilePicture: "Фото профиля",
    registryDate: "Дата регистрации",
    remarks: "Примечания",
    discard: "Отменить",
    confirmRegistry: "Подтвердить регистрацию",
    updateProfile: "Обновить профиль",
    clearSelection: "Очистить выбор",
    noEntries: "Записи не найдены",
    noEntriesSub: "Создайте первый профиль сотрудника или измените фильтры.",
    createProfile: "Создать профиль",
    personnel: "Сотрудник",
    privatePractice: "Частная практика",
    filteredView: "Фильтрованный вид",
    fullDatabaseIndex: "Полный индекс базы данных",
    masterDirectory: "Справочник команды",
    allRecordsLabel: "Весь персонал",
    darkUI: "Темная тема",
    lightUI: "Светлая тема",
    toggleTheme: "Переключить тему интерфейса",
    tools: "Приложения компании",
    launchTool: "Запустить",
    addTool: "Добавить",
    toolUrl: "URL приложения",
    toolName: "Название",
    browserError: "Если приложение не подключается, возможно, оно блокирует встроенный просмотр.",
    openExternal: "Открыть в новой вкладке",
    overview: "Обзор компании",
    revenue: "Общий доход",
    activeProjects: "Активные проекты",
    teamGrowth: "Рост команды",
    efficiency: "Эффективность",
    quickApps: "Приложения",
    performance: "Динамика эффективности",
    timeline: "Хронология прогресса",
    mindmap: "Интеллект-карта",
    sales: "Продажи и продукты",
    marketing: "Маркетинг",
    planning: "Комната планирования",
    document: "Стратегический документ",
    simulation: "Симулятор"
  },
  ar: {
    title: "WingMentor HQ",
    masterDatabase: "عمليات",
    sortLogic: "منطق الفرز",
    company: "الشركة",
    position: "المنصب",
    custom: "مخصص",
    allRecords: "جميع السجلات",
    customLists: "القوائم المخصصة",
    groups: "المجموعات",
    status: "الحالة",
    synced: "تم المزامنة",
    saving: "جاري الحفظ...",
    entries: "مدخلات",
    searchPlaceholder: "بحث...",
    addRecord: "إضافة سجل",
    settings: "إعدادات النظام",
    appearance: "المظهر",
    language: "اللغة",
    maintenance: "الصيانة",
    purgeDatabase: "استعادة قاعدة البيانات",
    factoryReset: "إعادة ضبط المصنع",
    closeSettings: "إغلاق الإعدادات",
    modify: "تعديل",
    erase: "مسح",
    joined: "انضم",
    dbRegistry: "سجل البيانات",
    identity: "الهوية",
    action: "إجراء",
    givenName: "الاسم الأول",
    surname: "اللقب",
    emailAddress: "البريد الإلكتروني",
    phone: "رقم الهاتف",
    profilePicture: "صورة الملف الشخصي",
    registryDate: "تاريخ التسجيل",
    remarks: "ملاحظات",
    discard: "تجاهل",
    confirmRegistry: "تأكيد التسجيل",
    updateProfile: "تحديث الملف الشخصي",
    clearSelection: "مسح التحديد",
    noEntries: "لم يتم العثور على سجلات",
    noEntriesSub: "قم بإنشاء أول ملف شخصي لموظف أو اضبط الفلاتر الخاصة بك.",
    createProfile: "إنشاء ملف شخصي",
    personnel: "موظف",
    privatePractice: "ممارسة خاصة",
    filteredView: "عرض مفلتر",
    fullDatabaseIndex: "فهرس قاعدة البيانات الكامل",
    masterDirectory: "دليل الفريق",
    allRecordsLabel: "كل الموظفين",
    darkUI: "واجهة داكنة",
    lightUI: "واجهة فاتحة",
    toggleTheme: "تبديل سمة النظام",
    tools: "تطبيقات الشركة",
    launchTool: "تشغيل الأداة",
    addTool: "إضافة أداة",
    toolUrl: "رابط التطبيق",
    toolName: "اسم التطبيق",
    browserError: "إذا رفض التطبيق الاتصال، فقد يكون يحظر العرض المضمن.",
    openExternal: "فتح في علامة تبويب جديدة",
    overview: "نظرة عامة للشركة",
    revenue: "إجمالي الإيرادات",
    activeProjects: "مشاريع نشطة",
    teamGrowth: "نمو الفريق",
    efficiency: "نقاط الكفاءة",
    quickApps: "تطبيقات سريعة",
    performance: "مسار الأداء",
    timeline: "الجدول الزمني للتقدم",
    mindmap: "الخريطة الذهنية",
    sales: "المبيعات والمنتجات",
    marketing: "التسويق",
    planning: "غرفة التخطيط",
    document: "وثيقة الاستراتيجية",
    simulation: "محاكي"
  },
  zh: {
    title: "WingMentor 总部",
    masterDatabase: "运营",
    sortLogic: "排序逻辑",
    company: "公司",
    position: "职位",
    custom: "自定义",
    allRecords: "所有记录",
    customLists: "自定义列表",
    groups: "分组",
    status: "状态",
    synced: "已同步",
    saving: "保存中...",
    entries: "条目",
    searchPlaceholder: "搜索...",
    addRecord: "添加记录",
    settings: "系统设置",
    appearance: "外观",
    language: "语言",
    maintenance: "维护",
    purgeDatabase: "还原数据库",
    factoryReset: "恢复出厂设置",
    closeSettings: "关闭设置",
    modify: "修改",
    erase: "擦除",
    joined: "加入日期",
    dbRegistry: "数据库注册",
    identity: "身份",
    action: "操作",
    givenName: "名字",
    surname: "姓氏",
    emailAddress: "电子邮件",
    phone: "电话号码",
    profilePicture: "个人头像",
    registryDate: "注册日期",
    remarks: "备注",
    discard: "放弃",
    confirmRegistry: "确认注册",
    updateProfile: "更新个人资料",
    clearSelection: "清除选择",
    noEntries: "未找到条目",
    noEntriesSub: "创建您的第一个员工档案或调整过滤器。",
    createProfile: "创建档案",
    personnel: "员工",
    privatePractice: "私人执业",
    filteredView: "过滤视图",
    fullDatabaseIndex: "完整数据库索引",
    masterDirectory: "团队名录",
    allRecordsLabel: "所有人员",
    darkUI: "深色界面",
    lightUI: "浅色界面",
    toggleTheme: "切换系统界面主题",
    tools: "公司应用",
    launchTool: "启动工具",
    addTool: "添加工具",
    toolUrl: "应用网址",
    toolName: "应用名称",
    browserError: "如果应用程序拒绝连接，它可能阻止了嵌入式视图。",
    openExternal: "在新标签页中打开",
    overview: "公司概况",
    revenue: "总收入",
    activeProjects: "活跃项目",
    teamGrowth: "团队增长",
    efficiency: "效率得分",
    quickApps: "快速应用",
    performance: "绩效轨迹",
    timeline: "进度时间表",
    mindmap: "思维导图",
    sales: "销售与产品",
    marketing: "市场营销",
    planning: "规划室",
    document: "战略文件",
    simulation: "模拟器"
  },
  ja: {
    title: "WingMentor 本部",
    masterDatabase: "オペレーション",
    sortLogic: "ソートロジック",
    company: "会社",
    position: "役職",
    custom: "カスタム",
    allRecords: "すべての記録",
    customLists: "カスタムリスト",
    groups: "グループ",
    status: "ステータス",
    synced: "同期済み",
    saving: "保存中...",
    entries: "エントリ",
    searchPlaceholder: "検索...",
    addRecord: "記録を追加",
    settings: "システム設定",
    appearance: "外観",
    language: "言語",
    maintenance: "メンテナンス",
    purgeDatabase: "データベースを復元",
    factoryReset: "初期状態にリセット",
    closeSettings: "設定を閉じる",
    modify: "修正",
    erase: "削除",
    joined: "入社日",
    dbRegistry: "DB登録日",
    identity: "アイデンティティ",
    action: "アクション",
    givenName: "名",
    surname: "姓",
    emailAddress: "メールアドレス",
    phone: "電話番号",
    profilePicture: "プロフィール写真",
    registryDate: "登録日",
    remarks: "備考",
    discard: "破棄",
    confirmRegistry: "登録を確認",
    updateProfile: "プロフィールを更新",
    clearSelection: "選択を解除",
    noEntries: "エントリが見つかりません",
    noEntriesSub: "最初の従業員プロファイルを作成するか、フィルターを調整してください。",
    createProfile: "プロファイルを作成",
    personnel: "従業員",
    privatePractice: "プライベートプラクティス",
    filteredView: "フィルター済みビュー",
    fullDatabaseIndex: "全データベースインデックス",
    masterDirectory: "チームディレクトリ",
    allRecordsLabel: "全職員",
    darkUI: "ダーク UI",
    lightUI: "ライト UI",
    toggleTheme: "システムのテーマを切り替える",
    tools: "企業アプリ",
    launchTool: "ツールを起動",
    addTool: "ツールを追加",
    toolUrl: "アプリURL",
    toolName: "アプリ名",
    browserError: "アプリケーションが接続を拒否する場合、埋め込みビューをブロックしている可能性があります。",
    openExternal: "新しいタブで開く",
    overview: "会社概要",
    revenue: "総収益",
    activeProjects: "アクティブなプロジェクト",
    teamGrowth: "チームの成長",
    efficiency: "効率スコア",
    quickApps: "クイックアプリ",
    performance: "パフォーマンスの軌跡",
    timeline: "進捗タイムライン",
    mindmap: "マインドマップ",
    sales: "販売＆製品",
    marketing: "マーケティング",
    planning: "企画室",
    document: "戦略文書",
    simulation: "シミュレータ"
  },
  ko: {
    title: "WingMentor 본부",
    masterDatabase: "운영",
    sortLogic: "정렬 로직",
    company: "회사",
    position: "직책",
    custom: "사용자 정의",
    allRecords: "모든 기록",
    customLists: "사용자 목록",
    groups: "그룹",
    status: "상태",
    synced: "동기화됨",
    saving: "저장 중...",
    entries: "항목",
    searchPlaceholder: "검색...",
    addRecord: "기록 추가",
    settings: "시스템 설정",
    appearance: "테마",
    language: "언어",
    maintenance: "유지 관리",
    purgeDatabase: "데이터베이스 복원",
    factoryReset: "초기화",
    closeSettings: "설정 닫기",
    modify: "수정",
    erase: "삭제",
    joined: "가입일",
    dbRegistry: "DB 등록일",
    identity: "신원",
    action: "작업",
    givenName: "이름",
    surname: "성",
    emailAddress: "이메일 주소",
    phone: "전화번호",
    profilePicture: "프로필 사진",
    registryDate: "등록 날짜",
    remarks: "비고",
    discard: "취소",
    confirmRegistry: "등록 확인",
    updateProfile: "프로필 업데이트",
    clearSelection: "선택 해제",
    noEntries: "항목을 찾을 수 없습니다",
    noEntriesSub: "첫 번째 직원 프로필을 생성하거나 필터를 조정하십시오.",
    createProfile: "프로필 생성",
    personnel: "직원",
    privatePractice: "개인 업무",
    filteredView: "필터링된 보기",
    fullDatabaseIndex: "전체 데이터베이스 색인",
    masterDirectory: "팀 디렉토리",
    allRecordsLabel: "모든 직원",
    darkUI: "다크 UI",
    lightUI: "라이트 UI",
    toggleTheme: "시스템 테마 전환",
    tools: "회사 앱",
    launchTool: "도구 실행",
    addTool: "도구 추가",
    toolUrl: "앱 URL",
    toolName: "앱 이름",
    browserError: "애플리케이션이 연결을 거부하면 임베디드 뷰를 차단할 수 있습니다.",
    openExternal: "새 탭에서 열기",
    overview: "회사 개요",
    revenue: "총 수익",
    activeProjects: "진행 중인 프로젝트",
    teamGrowth: "팀 성장",
    efficiency: "효율성 점수",
    quickApps: "빠른 앱",
    performance: "성과 궤적",
    timeline: "진행 일정",
    mindmap: "마인드맵",
    sales: "영업 및 제품",
    marketing: "마케팅",
    planning: "기획실",
    document: "전략 문서",
    simulation: "시뮬레이터"
  }
};
    